### ISSUE TITLE
If I press back button very fast, onBackPress is ignored.

### ISSUE THREAD

**Issue by ohjeyong** [vonovak/react-navigation-backhandler#12]
Let's say app has StackNavigator and there are two stacks S1, S2.
Let's say S1 is my app's base screen. I wrapped AndroidBackHandler on S1 component not to close app when user press back button.
In S1, if I press back button, then onBackPress function works great! 
After I push S2, if I press back button, then S2 disappear. If I press back button on S1, then onBackPress function works.
However, after I push S2 screen, then if I press back button twice very fast, then app closed without calling onBackPress function.

I think If I press back button twice very fast, the second back event is triggered before AndroidBackHandler attach didFocus event on S1.

**Comment by vonovak** [comment]
hi, thanks for reporting! can you try subscribing for `willFocus` instead of `didFocus`?

**Comment by ohjeyong** [comment]
@vonovak 
It solves the problem. Will it be better if this "react-native-backhandler" package use `willFocus` rather than `didFocus`?

**Comment by vonovak** [comment]
@ohjeyong yes please, if you could make a PR for this, that would be nice. thanks

**Comment by ohjeyong** [comment]
@vonovak I have submitted pull request. #13  Thanks.
