### ISSUE TITLE
Support newer react-navigation

### ISSUE THREAD

**Issue by lucasff** [vonovak/react-navigation-backhandler#14]
On the peer dependencies only version 1 and 2 are supported, thus I'm having this warning:
`warning " > react-navigation-backhandler@1.3.1" has incorrect peer dependency "react-navigation@^1.0.0 || ^2.0.0".`

Could you please update the peer dependency on your package.json?

**Comment by vonovak** [comment]
hi, thanks for reporting, this is fixed in v1.3.2

**Comment by zisheng-ai** [comment]
support react-navigation 5
