### ISSUE TITLE
Version 1.3.2 mysteriously ignores previously nested <AndroidBackHandler /> no matter what

### ISSUE THREAD

**Issue by Nantris** [vonovak/react-navigation-backhandler#19]
Admittedly our use case is not exclusively within a `StackNavigator` but none of our code has changed. 

Unfortunately upon revisiting the project the nested `AndroidBackHandler`s are totally ignored, not run at all, and only the highest level `onBackPress` is captured and run. 

Returning `false`, `true` at the highest level has no effect, and any other actions in nested handlers don't work to preempt this because the functions simply aren't run. Any thoughts would be greatly appreciated because we're otherwise looking at a huge amount of unexpected work and rethinking of our application.

I've examined my `yarn.lock` to try to find differences in version of this package or `react-navigation` packages, but I don't see anything wrong there either.

**Comment by Nantris** [comment]
Upgrading to `1.4.0` fixed one nested back handler, so I thought we were home free. Unfortunately, it broke another. -_-

**Comment by vonovak** [comment]
hello and thanks for reporting! Indeed, outside of Stack I'm not even sure how this works, but this might be an opportunity to get it to work somehow. However, to be able to help, I need to have some runnable code that I can work with and test the different use cases. Would you be able to provide this? Thanks!

**Comment by Nantris** [comment]
Hey @vonovak thanks for your reply. 

Unfortunately the runnable code is a bit too complex to put together a repro. I never figured out _why_ this happens, but I ended up with a workaround until we upgrade to React-Navigation 5. It's not pretty, but it doesn't need to scale. Hope it helps someone.


To give an example in case anyone else hits this:

(We upgraded to `1.4.0` which isn't necessary I think, but mentioning for completeness.)

```js
    if (navigator.state.nav.routes
       .find(route => route.routeName === 'mainStack')
        .routes.find(route => route.routeName === 'innerNav')
        .routes.find(route => route.routeName === 'myScreen').isDrawerOpen) 
            NavigationService.DrawerActions.closeDrawer()
```
