### ISSUE TITLE
BackHandler listener not removed

### ISSUE THREAD

**Issue by londonoliver** [vonovak/react-navigation-backhandler#4]
When calling `navigation.popToTop()` in a StackNavigator, `willUnmount` is called before `willBlur`, and the BackHandler listener is not removed.

**Comment by vonovak** [comment]
hi @londonoliver, thanks for reporting. For the record, the problem is that `willUnmount` is called first and removes the `willBlur` subscription and the `BackHandler.removeEventListener` in `willBlur` is therefore not called.
