### ISSUE TITLE
onBackButtonPressAndroid not call after back button press [react native 56]

### ISSUE THREAD

**Issue by idanlevi1** [vonovak/react-navigation-backhandler#7]
The original BackHandler not working (the event listener not call)
So i try to use `react-navigation-backhandler` but is don't play `onBackButtonPressAndroid` function
I'm wondering maybe its because react native version? and what can i do?

**Comment by ShuChangSC** [comment]
I hava the same problem,my RN version is 0.55.4 and react-navigation is 2.11.2,Have you solved it?

**Comment by Shivendra30** [comment]
I am also having the same problem, the function passed to the backhandler is not being called.
Wondering what I'm doing wrong...
@ShuChangSC , @idanlevi1 , did you guys solve it? If yes, please post the solution here :)

**Comment by idanlevi1** [comment]
I didn't solve it yet, but in my new application, it's work good.
the version:
```
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-navigation": "^2.18.2",
```

**Comment by rakakhrl** [comment]
@idanlevi1 Hey im having the same issue, my code is working before i build the app, but when i build the app it doesnt work and Im having the same version as you. Can you show me your onBackButtonPressAndroid function?

**Comment by vonovak** [comment]
I'm closing this because there is no repro of the issue, thanks. If the problem persists, please open a new issue with a repro. Thanks.
